# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: welcome to site youns
email: younes.saravari@yahoo.com
description: > # this means to ignore newlines until "baseurl:"
  سایت یونس سروری 
  
baseurl: "" # the subpath of your site, e.g. /blog
url: "sarvari72.ir" # the base hostname & protocol for your site
twitter_username: 
github_username: youns

# Build settings
markdown: kramdown
